// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Jaguar6CIMs.subsystems;

import org.usfirst.frc5112.Jaguar6CIMs.RobotMap;
import org.usfirst.frc5112.Jaguar6CIMs.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Drivetrain extends Subsystem {

    private final RobotDrive robotDrive = RobotMap.robotDrive;

    public double speed = 0.25;

    public void initDefaultCommand() {
        setDefaultCommand(new StopDrivetrain());
    }
    
    public void forwards(double speed) {
    	robotDrive.drive(speed, 0);
    }
    public void backwards(double speed) {
    	forwards(-speed);
    }
    public void stop() {
    	robotDrive.stopMotor();
    }
    public void increaseSpeed() {
    	if (speed <= 0.95) {
			speed = speed + 0.05;
		} else {
			speed = 1.0;
		}
    }
    
    public void decreaseSpeed() {
    	if (speed >= 0.05) {
    		speed = speed - 0.05;
    	}
    	else {
    		speed = 0.0;
    	}
    }
    
    public void updateSpeedSmardDashboard() {
    	SmartDashboard.putNumber("Drivetrain Speed: ", speed);
    }
}

