// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Jaguar6CIMs;

import org.usfirst.frc5112.Jaguar6CIMs.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton3;
    public JoystickButton joystickButton4;
    public JoystickButton joystickButton5;
    public JoystickButton joystickButton6;
    public Joystick joystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick = new Joystick(0);
        
        joystickButton6 = new JoystickButton(joystick, 6);
        joystickButton6.whileHeld(new DecreaseDirvetrainSpeed());
        joystickButton5 = new JoystickButton(joystick, 5);
        joystickButton5.whileHeld(new IncreaseDrivetrainSpeed());
        joystickButton4 = new JoystickButton(joystick, 4);
        joystickButton4.whileHeld(new DriveBackwards());
        joystickButton3 = new JoystickButton(joystick, 3);
        joystickButton3.whileHeld(new DriveForwards());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveForwards", new DriveForwards());
        SmartDashboard.putData("DriveBackwards", new DriveBackwards());
        SmartDashboard.putData("IncreaseDrivetrainSpeed", new IncreaseDrivetrainSpeed());
        SmartDashboard.putData("DecreaseDirvetrainSpeed", new DecreaseDirvetrainSpeed());
        SmartDashboard.putData("StopDrivetrain", new StopDrivetrain());
        Robot.drivetrain.updateSpeedSmardDashboard();

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick() {
        return joystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

