// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Jaguar6CIMs.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5112.Jaguar6CIMs.Robot;

public class DecreaseDirvetrainSpeed extends Command {

    public DecreaseDirvetrainSpeed() {
        requires(Robot.drivetrain);
    }

    protected void initialize() {
    	Robot.drivetrain.stop();
    	Robot.drivetrain.decreaseSpeed();
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return true;
    }

    protected void end() {
    	Robot.drivetrain.stop();
    }

    protected void interrupted() {
    	end();
    }
}
